name: CI

on:
    push:
    pull_request:
    release:
        types:
            - published

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                php: [8.4]
                laravel: [10.*, 11.*, 12.*]
                os: [ubuntu-latest]
                coverage: [none]
                include:
                    - laravel: 12.*
                      coverage: xdebug

        name: 'PHP ${{ matrix.php }} | Laravel ${{ matrix.laravel }}'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, json, openssl
                  ini-values: memory_limit=-1
                  tools: composer:v2
                  coverage: ${{ matrix.coverage }}

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-${{ matrix.php }}-composer-

            - name: Install Dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: 'laravel/framework:${{ matrix.laravel }}'

            - name: Execute tests
              if: matrix.coverage == 'none'
              run: composer test

            - name: Run Quality Checks and Coverage
              if: matrix.coverage == 'xdebug'
              run: composer ci

            - name: Upload Coverage to Codecov
              if: matrix.coverage == 'xdebug'
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

            - name: Upload Test Results to Codecov
              if: matrix.coverage == 'xdebug'
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true
